### ISSUE TITLE
Problem when running sudo ldconfig

### ISSUE THREAD

**Issue by iiiiishan** [LELEC210X/LELEC210X#11]
We have the following message when we try to do sudo ldconfig to flash the lime: 
![image](https://github.com/LELEC210X/LELEC210X/assets/145784812/e6257c6a-d0bd-4572-b924-29d78a235cb3)

**Comment by jeertmans** [comment]
Hello @iiiiishan, do you find a solution to this problem, or is it still an issue?

**Comment by jeertmans** [comment]
Closing as stalled, please re-open this issue if you encounter it.
