### ISSUE TITLE
ERROR - USB pass-through to connect LimeSDR to WSL

### ISSUE THREAD

**Issue by colinrenard** [LELEC210X/LELEC210X#20]
In the INSTALL.md file, the following commands raise the error "usbipd: error: The 'wsl' subcommand has been removed. Learn about the new syntax at https://learn.microsoft.com/windows/wsl/connect-usb#attach-a-usb-device." : 

```
usbipd wsl list
usbipd wsl attach --busid <busid>
usbipd wsl detach --busid <busid>
```

Commands in the mentioned link (https://learn.microsoft.com/fr-fr/windows/wsl/connect-usb#attach-a-usb-device) seem to work:

```
usbipd list
usbipd bind --busid 4-4
usbipd attach --wsl --busid <busid>
usbipd detach --busid <busid> 
```

**Comment by jeertmans** [comment]
Thanks @colinrenard!
