### ISSUE TITLE
PortAudio not found

### ISSUE THREAD

**Issue by Rauwla** [LELEC210X/LELEC210X#27]
Hello, 

While trying to run h1_feature_vectors with rye, the following error appears (see the image).
![Screenshot from 2024-09-21 18-56-22](https://github.com/user-attachments/assets/2f6b40dd-3a99-4a96-9f0e-921eb464cc68)

Can you help me? 
Thanks

**Comment by jeertmans** [comment]
Hello @Rauwla, it means that you have to install PortAudio libraries, see https://github.com/Upsonic/gpt-computer-assistant/issues/22#issuecomment-2147378454.

What OS / platform are you using? WSL / Linux / macOS ?

**Comment by Rauwla** [comment]
Thanks I followed the instructions and now it works!

**Comment by jeertmans** [comment]
Happy it works! Can you just let me know what OS / platform you are using?

**Comment by Rauwla** [comment]
Of course, I'm using Linux.

**Comment by jeertmans** [comment]
Native Linux (like a dualboot), or Linux in a Virtual Box / inside WSL?

**Comment by Rauwla** [comment]
Yes it's a dualboot so native linux

**Comment by jeertmans** [comment]
Thanks!
