### ISSUE TITLE
Errors of includes while building the hands_on_audio_acquisition

### ISSUE THREAD

**Issue by ppasture** [LELEC210X/LELEC210X#32]
Hello,

We tried to build the hands_on_audio_acquisition for the H2b part of the project but we get some issues with including the "stm32l4xx_hal.h" and "stm32l4xx.h" with "no such file or directory". We have already installed Software Package stm32l4 for the hands_on_mcu from last week.

Thank you!

**Comment by jeertmans** [comment]
Hello @ppasture, please recreate this issue using the [bug template](https://github.com/LELEC210X/LELEC210X/issues/new?assignees=&labels=bug&projects=&template=bug.yml&title=%3Cshort-description-here%3E), as it helps us narrow down the issue, and also makes triage easier.

I am locking this issue so we will only use the comment on one issue :-)
