### ISSUE TITLE
PortAudioError: Error querying device -1

### ISSUE THREAD

**Issue by chrenson** [LELEC210X/LELEC210X#4]
Bonjour, 
Lorsque je joue les sons du jupyter notebook, cette erreur s'affiche. Je suis sur WSL. 
Merci

![erreur](https://github.com/LELEC210X/LELEC210X/assets/100871119/cfff2c08-98e5-4247-965a-6e7b8d5c7d9d)

**Comment by jeertmans** [comment]
Unfortunately, WSL does not support audio, so there is no solution to this on WSL.
In practice, you can play the audio files manually if you want :-)

However, you can install Poetry (and all the Python packages) directly on Windows: see the docs ["*Windows (Powershell)*"](https://python-poetry.org/docs/).
