### ISSUE TITLE
Error when compiling the project on quartus

### ISSUE THREAD

**Issue by lraviart** [LELEC210X/LELEC210X#49]
### Terms

- [X] Checked the [existing issues](https://github.com/LELEC210X/LELEC210X/issues?q=is%3Aissue) and [discussions](https://github.com/LELEC210X/LELEC210X/discussions) to see if my issue had not already been reported;
- [X] Read the [best practice](https://github.com/LELEC210X/LELEC210X/wiki/Best-practice-guide) and checked if my bug was not one of the common bugs documented in the Wiki;
- [X] Updated my Python virtual environment with `rye sync`;

### Describe the issue

When trying to compile the design on Quartus, errors appear and I am unable to compile it. This is also the case for all the members of our group. We think we did all the steps described in the H4 assignment.

### Command or program

Quartus

### Issue Type

Error when running an command

### What is your platform?

Windows

### Screenshots

![image](https://github.com/user-attachments/assets/1ca27078-f1ae-4a59-8a46-601e1eb62700)
![image](https://github.com/user-attachments/assets/8cdcaf29-3d39-4b5f-adfc-a338ebe61491)

### Additional information

We tried it with the design from our forked github and from the original one so we don't think it is an update problem.

**Comment by lraviart** [comment]
We found the problem, when opening the project Quartus offers to do an IP upgrade which causes the error. The fix is simply not to do it. 
![image](https://github.com/user-attachments/assets/3ea8b961-32d9-4178-bd98-3c6f11a9a9bb)

**Comment by jeertmans** [comment]
It indeed reminds me of some problem we encountered in the past. Glad you found the solution :)
