### ISSUE TITLE
Virtualbox : Can't attach USB device

### ISSUE THREAD

**Issue by IMightBeAPerson** [LELEC210X/LELEC210X#8]
Hello, I can not attatch the Lime SDR to the virtual box
![image](https://github.com/LELEC210X/LELEC210X/assets/145764759/f128864d-67a7-4121-9953-00478c04124e)

**Comment by IMightBeAPerson** [comment]
Needed to change USB controller to USB 3.0 while the machine was off.

**Comment by jeertmans** [comment]
You mean just to unplug the LimeSDR? Or to change in the VM settings?

Happy you solved your issue :-)

**Comment by IMightBeAPerson** [comment]
I powered off the VM so I could change the settings
